/*
 * KOSIF — فهرس المعايير
 *
 * معايير التقرير المالي (IFRS/IAS كما تعتمدها الهيئة السعودية للمراجعين
 * والمحاسبين) ومعايير المراجعة (ISA). لكل معيار حقل lastUpdate يذكر آخر
 * تعديل جوهري، ورابط المصدر الرسمي — فالتطبيق يربط النتيجة بالمعيار وبتاريخ
 * سريانه، لا باسمه فقط.
 *
 * تنبيه صريح: تواريخ التعديلات هنا مرجع عمل وليست نصًا نظاميًا. الروابط
 * الرسمية هي المرجع النهائي، ويعرضها التطبيق مع كل استشهاد.
 */

export const CATALOG_VERSION = '1.0.0';
export const CATALOG_REVIEWED = '2026-08-31';

/** معايير التقرير المالي المعتمدة في المملكة. */
export const REPORTING_STANDARDS = Object.freeze([
  Object.freeze({"code":"IAS 1","framework":"ifrs","en":"Presentation of Financial Statements","ar":"عرض القوائم المالية","purpose":"الإطار العام لعرض القوائم المالية ومحتوياتها: متطلبات الاكتمال، العرض العادل، الاستمرارية، أساس الاستحقاق، ثبات عرض البنود، والمقارنات. وهو المعيار المرجعي لأي بند لا ينص عليه معيار خاص.","relation":"يُطبق على الميزان ككل: من حيث هيكل البنود، ترتيب الأصول والالتزامات (متداول / غير متداول)، واكتمال الإفصاحات المصاحبة.","lastUpdate":"تعديلات «تصنيف الالتزامات المتداولة وغير المتداولة» والتعهدات — سارٍ من 1/1/2024 (وأصدر مجلس المعايير IFRS 18 الذي سيحل محله ابتداءً من 1/1/2027)","source":"https://www.ifrs.org/issued-standards/list-of-standards/ias-1-presentation-of-financial-statements/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["عرض","قوائم","ميزان","إفصاح"],"keywords":[]}),
  Object.freeze({"code":"IAS 2","framework":"ifrs","en":"Inventories","ar":"المخزون","purpose":"قياس المخزون وتكلفته (الأقل بين التكلفة وصافي القيمة القابلة للتحقق)، وقواعد إثبات مصروف استهلاك المخزون في تكلفة المبيعات.","relation":"يحكم بنود المخزون (بضاعة موجودة، مواد خام، تحت التشغيل): ربطها بالتكلفة المناسبة وإمكانية بيعها بأكثر من قيمتها الدفترية.","lastUpdate":"آخر تغيير جوهري ضمن مشروع تعديل الإفصاح عن الإيرادات والمخزون (2018)","source":"https://www.ifrs.org/issued-standards/list-of-standards/ias-2-inventories/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["مخزون","بضاعة","تكلفة مبيعات"],"keywords":["مخزون","مخازن","بضاعة","مواد خام","تحت التشغيل","بضاعة بالطريق","تغليف"]}),
  Object.freeze({"code":"IAS 7","framework":"ifrs","en":"Statement of Cash Flows","ar":"قائمة التدفقات النقدية","purpose":"عرض حركة النقد وما يعادله خلال الفترة في أنشطة تشغيلية واستثمارية وتمويلية.","relation":"يحكم بنود النقدية وما يعادلها وأثر العمليات عليها، ويستخدم للتحقق من منطقية صافي التغير في النقدية مقابل الأرصدة.","lastUpdate":"بدون تغييرات جوهرية حديثة على هذا المعيار","source":"https://www.ifrs.org/issued-standards/list-of-standards/ias-7-statement-cash-flows/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["نقدية","تدفقات","بنك"],"keywords":["نقدية","صندوق","بنك","مصرف","نقد ومعادل"]}),
  Object.freeze({"code":"IAS 8","framework":"ifrs","en":"Accounting Policies, Changes in Accounting Estimates and Errors","ar":"السياسات المحاسبية والتغيرات في التقديرات المحاسبية والأخطاء","purpose":"أساس اختيار السياسات وكيفية معالجة تغيّر التقديرات والأخطاء الجوهرية بشكل بأثر رجعي.","relation":"يحكم أي اعتماد على تقديرات محاسبية في الميزان (إهلاك، مخصصات) وتصحيح الأخطاء عند اكتشافها في مرحلة المراجعة.","lastUpdate":"تسمية المعيار عُدلت إلى «التقديرات المحاسبية» وتعريفها (تعديلات 2021 — نافذة 1/1/2023)","source":"https://www.ifrs.org/issued-standards/list-of-standards/ias-8/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["سياسات","أخطاء","تقديرات"],"keywords":["تصحيح","خطأ","سابق سنوات","تسوية"]}),
  Object.freeze({"code":"IAS 10","framework":"ifrs","en":"Events after the Reporting Period","ar":"الأحداث اللاحقة لفترة التقرير","purpose":"معالجة الأحداث الواقعة بعد تاريخ الميزان: معدِّلة تتطلب إعادة عرض، وغير معدِّلة تتطلب إفصاحًا.","relation":"يلزم المجلس بتساؤل الإدارة عن أي أحداث بعد تاريخ الميزان تمس بنود الميزان (كسداد ذمم أو خسائر مخزون لاحقة).","lastUpdate":"بدون تغييرات جوهرية حديثة","source":"https://www.ifrs.org/issued-standards/list-of-standards/ias-10-events-after-the-reporting-period/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["أحداث لاحقة"],"keywords":["أحداث لاحقة"]}),
  Object.freeze({"code":"IAS 12","framework":"ifrs","en":"Income Taxes","ar":"ضرائب الدخل","purpose":"محاسبة ضرائب الدخل الحالية والمؤجلة بناء على الأصول والالتزامات، والاعتراف بأصول الضريبة المؤجلة عند الاحتمال الراجح.","relation":"يحكم بند ضريبة الدخل المستحقة وفروقاتها المؤقتة على أصول مثل الإهلاك والمخصصات، وبند «ضرائب مؤجلة» إن وجد.","lastUpdate":"بدون تغييرات جوهرية؛ مع عمليات تطوير مستمرة مرتبطة بمشروع ضرائب الاقتراض العالمي (Pillar Two — إعفاء مؤقت نافذ منذ 2023)","source":"https://www.ifrs.org/issued-standards/list-of-standards/ias-12-income-taxes/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["ضريبة","ضريبة دخل","ضريبة مؤجلة"],"keywords":["ضريبة","زكاة","ضريبة الدخل","ضرائب مؤجلة","ضريبة مستحقة"]}),
  Object.freeze({"code":"IAS 16","framework":"ifrs","en":"Property, Plant and Equipment","ar":"الممتلكات والآلات والمعدات","purpose":"قياس الأصول الملموسة طويلة الأجل بالتكلفة وتوزيع قابلة للاستهلاك منها على مدى العمر الإنتاجي بالإهلاك المنهجي.","relation":"يحكم بنود الآلات والمعدات والمباني والأثاث ومراكب النقل: رسملة التكاليف وطريقة ونسبة الإهلاك ومراجعة انخفاض القيمة.","lastUpdate":"تعديل استخدام ما قبل التشغيل (Proceeds before Intended Use — نافذ 1/1/2022)","source":"https://www.ifrs.org/issued-standards/list-of-standards/ias-16-property-plant-and-equipment/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["أصول ثابتة","إهلاك","ممتلكات"],"keywords":["أثاث","سيارات","آليات","آلات","مباني","أبنية","تركيبات","عقمات","مواصلات","عتاد","حاسوبا","أجهزة"]}),
  Object.freeze({"code":"IAS 19","framework":"ifrs","en":"Employee Benefits","ar":"مزايا الموظفين","purpose":"محاسبة جميع مزايا الموظفين ومنها مكافأة نهاية الخدمة: قياس الالتزام على أساس الاستحقاق التراكمي وسعر الخصم والفائدة الصافية على الالتزام.","relation":"يحكم بنود الرواتب والأجور المستحقة والإجازات المتراكمة ومخصص مكافأة نهاية الخدمة في المنشآت ذات النظم الداخلية المكفولة.","lastUpdate":"تعديل الإعفاء من متطلب تحديد نهاية خدمة الموظفين في حالة وجود نظام داخلي غير رسمي (نافذ 1/1/2024)","source":"https://www.ifrs.org/issued-standards/list-of-standards/ias-19-employee-benefits/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["رواتب","موظفين","نهاية خدمة"],"keywords":["رواتب","أجور","مكافأة نهاية","نهاية خدمة","موظفي","عاملين","إجازات مستحقة","تأمينات اجتماعية"]}),
  Object.freeze({"code":"IAS 21","framework":"ifrs","en":"The Effects of Changes in Foreign Exchange Rates","ar":"أثر تغيرات أسعار الصرف الأجنبي","purpose":"قياس العملات الأجنبية في المعاملات والأرصدة، وكيفية إدراج فروقات الصرف في النتائج.","relation":"يحكم بنود الذمم أو الحسابات أو القروض بعملات أجنبية: تقييم الأرصدة بأسعار الإغلاق وإثبات فروق الصرف.","lastUpdate":"بدون تغييرات جوهرية حديثة","source":"https://www.ifrs.org/issued-standards/list-of-standards/ias-21-the-effects-of-changes-in-foreign-exchange-rates/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["عملة أجنبية","صرف"],"keywords":["عملة أجنبية","عملات أجنبي","فروع خارجية","فرق عملة","بالتصدير"]}),
  Object.freeze({"code":"IAS 24","framework":"ifrs","en":"Related Party Disclosures","ar":"الإفصاح عن الأطراف ذات العلاقة","purpose":"إلزام القوائم بإفصاح كافٍ عن العلاقات والمعاملات والأرصدة مع الأطراف ذات العلاقة (شركاء، شركات شقيقة، إدارة).","relation":"يطلب المجلس تحليل بنود «جاري الشركاء» أو «سلف/تسبيقات» والتأكد من طبيعة العلاقة والشروط التجارية.","lastUpdate":"بدون تغييرات جوهرية حديثة","source":"https://www.ifrs.org/issued-standards/list-of-standards/ias-24-related-party-disclosures/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["أطراف علاقة","شركاء","شركات شقيقة"],"keywords":["شركاء","جاري الشركاء","مسحوبات شخصية","سلف شخصية","الحكومية","الشقيقة"]}),
  Object.freeze({"code":"IAS 33","framework":"ifrs","en":"Earnings per Share","ar":"ربح السهم الأساسي والمخفف","purpose":"حساب رقم ربح السهم للشركات المساهمة العامة وأساسه البند الوارد في قائمة الدخل.","relation":"مرتبط بصافي ربح الفترة عند الكشف عنه داخل ميزان أخطاء التصحيح لنتائج النشاط.","lastUpdate":"بدون تغييرات جوهرية حديثة","source":"https://www.ifrs.org/issued-standards/list-of-standards/ias-33-earnings-per-share/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["ربح سهم","أسهم"],"keywords":["ربح السهم","سهم","حقوق أصحاب"]}),
  Object.freeze({"code":"IAS 36","framework":"ifrs","en":"Impairment of Assets","ar":"انخفاض قيمة الأصول","purpose":"التأكد من عدم حمل الأصول في الدفاتر بأكثر من المبلغ المسترد (الأعلى بين القيمة العادلة مطروحًا منها تكاليف البيع وقيمة الاستخدام)، مع عملية اختبار للسمعة التجارية سنويًا.","relation":"يجعل بنود الأصول الثابتة والسمعة والأصول غير الملموسة موضوع اختبار انخفاض عند وجود مؤشرات (انخفاض نشاط، تقادم) ويطلب أدلة على ذلك.","lastUpdate":"لم يتغير جوهريًا؛ خضع لعديد مقررات تفاعل مع البرامج المتجددة","source":"https://www.ifrs.org/issued-standards/list-of-standards/ias-36-impairment-of-assets/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["انخفاض قيمة","سمعة"],"keywords":["سمعة تجاري","استموار","علامة تجاري","اختبار انخفاض","خسائر تدني","مخصص انخفاض"]}),
  Object.freeze({"code":"IAS 37","framework":"ifrs","en":"Provisions, Contingent Liabilities and Contingent Assets","ar":"مخصصات والالتزامات والأصول المحتملة","purpose":"الاعتراف بالمخصص فقط عندما يوجد التزام حالي نابع من حدث سابق، واحتمال نفاد الموارد أكبر من مجرد احتمال، وقابل للموثوقية بالقياس؛ والإفصاح عن الباقي المحتمل دون إثبات.","relation":"يحكم بنود «مخصصات» ودعاوى قضائية وضمانات وأغراض هدم وعمليات إيقاف معينة قد تظهر ضمن الميزان.","lastUpdate":"بدون تغييرات جوهرية حديثة","source":"https://www.ifrs.org/issued-standards/list-of-standards/ias-37-provisions-contingent-liabilities-and-contingent-assets/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["مخصصات","قضايا","ضمانات"],"keywords":["مخصص","مخصصات","دعاوي","قضايا","غرامات","ضمانات مشتركة","التزامات محتملة"]}),
  Object.freeze({"code":"IAS 38","framework":"ifrs","en":"Intangible Assets","ar":"الأصول غير الملموسة","purpose":"الاعتراف بالأصول غير المادية القابلة للتفريق (برمجيات، حق انتفاع، تراخيص) بالتكلفة، ولا يجوز رسملة الأصول المطورة داخليًا إلا بشروط استيفائية محددة.","relation":"يشمل بنود برامج الحاسوب وشروط الانتشار والحقوق المدفوعة، ويعتبرها أصولا غير ملموسة مطابقة للأصول الثابتة.","lastUpdate":"بدون تغييرات جوهرية حديثة","source":"https://www.ifrs.org/issued-standards/list-of-standards/ias-38-intangible-assets/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["غير ملموسة","برمجيات","تراخيص"],"keywords":["برامج","ترخيص","تراخيص","حق انتفاع","علامة تجارية","رخص","أنظمة محاسبية","مواقع إلكترونية"]}),
  Object.freeze({"code":"IAS 40","framework":"ifrs","en":"Investment Property","ar":"عقارات الاستثمار","purpose":"العقارات المحتفظ بها لكسب الإيجارات أو ارتفاع القيمة وليس للاستخدام الإداري؛ تقاس بالتكلفة أو نموذج القيمة العادلة مع الإفصاح.","relation":"يتطلب فرز عقارات الاستثمار عن الممتلكات الرأسمالية التشغيلية في الميزان والتنبيه على الاختلاف في طرق المعالجة.","lastUpdate":"بدون تغييرات جوهرية حديثة","source":"https://www.ifrs.org/issued-standards/list-of-standards/ias-40-investment-property/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["عقارات استثمار","إيجارات"],"keywords":["عقارات استثمار","أراضٍ للاستثمار","عقارات إيجارية"]}),
  Object.freeze({"code":"IFRS 3","framework":"ifrs","en":"Business Combinations","ar":"تراكم الأعمال","purpose":"قواعد محاسبة اقتناء الكيانات: منهجية الاستحواذ، تحديد السعر المشترى وتوزيعه على أصول والتزامات العميل بقيمة عادلة والسمعة المتبقية.","relation":"يهتم ببنود السمعة التجارية الناشئة عن اقتناء نشاط، ومبررات توزيع الثمن على الأصول المشتراة.","lastUpdate":"تعديل «الإشارة إلى افتراضات» ضمن مبادئ مقررة إغلاق الالتزامات المرتبطة بالمشتري (نافذ 1/1/2023)","source":"https://www.ifrs.org/issued-standards/list-of-standards/ifrs-3-business-combinations/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["استحواذ","سمعة تجارية"],"keywords":["استحواذ","اندماج","شراء أعمال","سمعة تجاري"]}),
  Object.freeze({"code":"IFRS 5","framework":"ifrs","en":"Non-current Assets Held for Sale and Discontinued Operations","ar":"الأصول غير المتداولة المحتفظ بها للبيع والأنشطة المتوقفة","purpose":"الأصول المرشحة للبيع الفوري يجب أن تُعرض منفصلة وبتقييم الأقل بين القيمة الدفترية والقيمة العادلة مطروحًا منها تكاليف البيع، وتوقف الإهلاك عليها.","relation":"يخص بنود الأصول «المعدة للبيع» أو الأنشطة المتوقفة الظاهرة في الميزان وجوباً تصنيفها وعروضها.","lastUpdate":"بدون تغييرات جوهرية حديثة","source":"https://www.ifrs.org/issued-standards/list-of-standards/ifrs-5-non-current-assets-held-for-sale-and-discontinued-operations/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["معد للبيع","نشاط موقوف"],"keywords":["محتفظ به للبيع","معدة للبيع","نشاط متوقف","تصفية فرع"]}),
  Object.freeze({"code":"IFRS 7","framework":"ifrs","en":"Financial Instruments: Disclosures","ar":"الأدوات المالية: الإفصاحات","purpose":"يحدد جميع الإفصاحات الهامة المرتبطة بالأدوات المالية: درجات المخاطر الائتمانية والسيولة والسوق، وتصنيف القياس والقيمة العادلة.","relation":"مكمل لتطبيق IFRS 9 على كل بنود الذمم والقروض والنقدية، ويسلب عدم كفاية إفصاح حدود الائتمان المستخدمة والأصول المتعثرة.","lastUpdate":"بدون تغييرات جوهرية حديثة","source":"https://www.ifrs.org/issued-standards/list-of-standards/ifrs-7-financial-instruments-disclosures/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["أدوات مالية","إفصاح"],"keywords":["أدوات مالي","مشتقات","مقايضة"]}),
  Object.freeze({"code":"IFRS 9","framework":"ifrs","en":"Financial Instruments","ar":"الأدوات المالية","purpose":"التصنيف والقياس بناء على نماذج الأعمال والتدفقات التعاقدية، وخفض شامل لخسائر الانحراف الائتمانية المتوقعة (ECL) على الذمم المدينة وأصول الأموال؛ ومحاسبة التحويلة (hedge accounting).","relation":"يحكم بنود الذمم المدينة والعملاء وأوراق القبض: تكوين مخصص خسائر ائتمانية متوقعة (حتى لو كانت صغيرة نسبة بساطة عملية)، وقواعد خصم القروض غير الملائمة.","lastUpdate":"بدون تغييرات جوهرية؛ مع مقررات توضيحية متتالية حول استبعاد مخصص ECL على السندات الخضراء","source":"https://www.ifrs.org/issued-standards/list-of-standards/ifrs-9-financial-instruments/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["ذمم مدينة","خسائر ائتمانية","قروض"],"keywords":["ذمم مدينة","مدينين","عملاء","أوراق قبض","قرض","قروض","تمويلي","خصوم سحب بالمكشوف","استثمارات"]}),
  Object.freeze({"code":"IFRS 13","framework":"ifrs","en":"Fair Value Measurement","ar":"قياس القيمة العادلة","purpose":"إطار موحد للقياس بالقيمة العادلة وإفصاح هرمية القيمة العادلة (مستوى 1، 2، 3) لما يقاس بها.","relation":"مساند للتقييمات في بنود استخدام القيمة العادلة: أصول استثمار ومشتقات وأصول اقتناء حديثة.","lastUpdate":"بدون تغييرات جوهرية حديثة","source":"https://www.ifrs.org/issued-standards/list-of-standards/ifrs-13-fair-value-measurement/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["قيمة عادلة"],"keywords":["قيمة عادلة","تقييم عقاري","تقييم أعمال"]}),
  Object.freeze({"code":"IFRS 15","framework":"ifrs","en":"Revenue from Contracts with Customers","ar":"الإيراد من العقود مع العملاء","purpose":"منهج خمس خطوات: تحديد العقد والتزامات الأداء وسعر المقابللة وتوزيعها والاعتراف بالإيراد عند/بحسب تسليم الالتزامات. المبادئ تفصل بيع المنتجات والخدمات والأوعية والمدفوعات المقدمة.","relation":"يحكم بند المدفوعات المقدمة من العملاء (التزام عقد) مقابل الاعتراف بالإيراد ومنطق حسابات «إيراد مقدماً». ويعرج أيضا على بنود الحوافز وهامش الوسطاء.","lastUpdate":"بدون تغييرات جوهرية حديثة","source":"https://www.ifrs.org/issued-standards/list-of-standards/ifrs-15-revenue-from-contracts-with-customers/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["إيراد","مبيعات","عملاء"],"keywords":["مبيعات","إيرادات","إيراد","عقود تنفيذ","رسوم خدمات","عمولات","دفعات مقدمة","مقدمات عملاء"]}),
  Object.freeze({"code":"IFRS 16","framework":"ifrs","en":"Leases","ar":"عقود الإيجار","purpose":"على المستأجر: أصل حق الاستخدام والتزام إيجاري لكل عقد إيجار مادي (لا إيجارات تشغيلية خارج القوائم)، وعلى المؤجر: حفاظ على نموذج التشغيل/التمويل.","relation":"يحيط ببنود الإيجارات: أصول «حق انتفاع» والتزامات الإيجار المقابلة، وفصل إهلاك الأصل عن فوائد الالتزام بدل مصروف إيجار مستقيم.","lastUpdate":"بدون تغييرات جوهرية حديثة على متطلبات المستأجر","source":"https://www.ifrs.org/issued-standards/list-of-standards/ifrs-16-leases/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["إيجار","حق انتفاع"],"keywords":["إيجار","ايجار","كراء","حق انتفاع","التزام إيجار","مكاتب مؤجر","معارض مؤجرة"]}),
  Object.freeze({"code":"IFRS 17","framework":"ifrs","en":"Insurance Contracts","ar":"عقود التأمين","purpose":"نموذج شامل لمحاسبة عقود التأمين: هامش الخدمة الحالي وإعادة العرض بحصص التغطية ومجموعات الأدوات المتوقفة.","relation":"خاص بمنشآت التأمين: يحكم بنود الأقساط المستحقة ومخصصات المطالبات عند ظهورها في ميزان قطاع التأمين.","lastUpdate":"بدء التطبيق 2023 مع تعديلات سرعة اعتماد قياس أداة سنوية اجتيازية (نافذة 2023-2024)","source":"https://www.ifrs.org/issued-standards/list-of-standards/ifrs-17-insurance-contracts/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["تأمين"],"keywords":["تأمين","تعويضات تأمين","محتجزات"]}),
  Object.freeze({"code":"IFRS 8","framework":"ifrs","en":"Operating Segments","ar":"المقاطع التشغيلية","purpose":"عرض البيانات المالية لحسب كيفيات تقييم المدير للقطاعات، تحت مظلة إيجاد الشركات العامة للتقطاعات والعملاء الجغرافيين.","relation":"كشف أفقي لدى المنشآت متعددة الأنشطة: تفكيك إجمالي ميزان المبيعات إلى قطاعات كعز ولوجستيات تفصيلية.","lastUpdate":"بدون تغييرات جوهرية حديثة","source":"https://www.ifrs.org/issued-standards/list-of-standards/ifrs-8-operating-segments/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["قطاعات","أنشطة"],"keywords":["قطاعات","فروع تشغيلية"]}),
  Object.freeze({"code":"IAS 27","framework":"ifrs","en":"Separate Financial Statements","ar":"القوائم المالية المنفردة","purpose":"محاسبة الاستثمارات في الشركات التابعة والزملاء والمشاريع المشتركة داخل قوائم المالك وحدها بالطريقة المعتمدة (بالتكلفة أو كأدوات مالية).","relation":"يبين طريقة عرض بنود «استثمار في شركة تابعة» أو «سهمية زمالة» داخل الميزان.","lastUpdate":"بدون تغييرات جوهرية حديثة","source":"https://www.ifrs.org/issued-standards/list-of-standards/ias-27-separate-financial-statements/","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["استثمارات تابعة","شركات شقيقة"],"keywords":["استثمار في شركات","تابعة","زمالة","مشروع مشترك"]}),
  Object.freeze({"code":"SOCPA-CO","framework":"ifrs","en":"Charter / Local Regulations & Zakat","ar":"الأطر النظامية المحلية (الزكاة والنظام السعودي)","purpose":"الأطر التنظيمية المحلية السعودية الملازمة للقوائم: الضوابط الزكوية وفقاً لأنظمة هيئة الزكاة والضريبة والجمارك، وضوابط المنطقة الاقتصادية الخاصة، مع ملاءمة الاستحقاقات المحاسبية للفصل بين الضريبة والزكاة.","relation":"يطلب المجلس في بيئة S.A.R استيضاح بنود الزكاة والضريبة (VAT) والعلاوات المستحقة ضمن الأرصدة الختامية.","lastUpdate":"تحديثات دورية من ZATCA — أحدثها أدلة متسلسلة الفوترة الإلكترونية الفاز الثاني (الربط والتكامل)","source":"https://zatca.gov.sa/ar/RulesRegulations/Taxes/Pages/default.aspx","localSource":"https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx","tags":["زكاة","ضريبة القيمة المضافة","نظامي"],"keywords":["ضريبة القيمة المضافة","vat","فاتورة إلكترونية","ضريبية مستحقة","مدخلات مضاعفة"]})
]);

/**
 * معايير المراجعة الدولية المستخدمة فعليًا في جولات هذا التطبيق.
 * كل معيار هنا مربوط بجولة أو أكثر في برنامج المراجعة، فلا يظهر معيار
 * لا يقود إلى إجراء.
 */
export const AUDITING_STANDARDS = Object.freeze([
  Object.freeze({ code: 'ISA 200', framework: 'isa', en: 'Overall Objectives of the Independent Auditor', ar: 'الأهداف العامة للمراجع المستقل',
    purpose: 'يحدد هدف المراجعة: الحصول على تأكيد معقول بأن القوائم خالية من التحريف الجوهري، والتقرير عنها. ويضع مفاهيم الشك المهني والحكم المهني.',
    relation: 'يحكم الارتباط ككل ويؤسس لكل جولة تالية.', lastUpdate: 'ساري بصيغته المعاد صياغتها (Clarity Project)',
    source: 'https://www.iaasb.org/publications/2023-handbook-international-quality-management-auditing-review-other-assurance-and-related-services', localSource: 'https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx',
    tags: ['إطار', 'شك مهني'], keywords: [] }),
  Object.freeze({ code: 'ISA 220', framework: 'isa', en: 'Quality Management for an Audit of Financial Statements', ar: 'إدارة الجودة لمراجعة القوائم المالية',
    purpose: 'مسؤوليات الشريك المسؤول عن الارتباط في إدارة الجودة، والإشراف والفحص، ومراجعة جودة الارتباط.',
    relation: 'يحكم جولة التقرير ومراجعة الجودة، ويشترط اعتمادًا بشريًا قبل إصدار الرأي.', lastUpdate: 'النسخة المنقحة سارية للفترات المنتهية في أو بعد 15/12/2022',
    source: 'https://www.iaasb.org/publications/international-standard-auditing-220-revised-quality-management-audit-financial-statements', localSource: 'https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx',
    tags: ['جودة', 'إشراف'], keywords: [] }),
  Object.freeze({ code: 'ISA 240', framework: 'isa', en: 'The Auditor’s Responsibilities Relating to Fraud', ar: 'مسؤوليات المراجع المتعلقة بالغش',
    purpose: 'افتراض وجود مخاطر غش في إثبات الإيراد، واختبار القيود اليومية، وتقييم تجاوز الإدارة للضوابط.',
    relation: 'يحكم أعلام مخاطر القيود واختبار بنفورد وفحص القيود غير المعتادة.', lastUpdate: 'قيد التنقيح لدى IAASB (مشروع ISA 240 المنقح)',
    source: 'https://www.iaasb.org/consultations-projects/fraud', localSource: 'https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx',
    tags: ['غش', 'قيود', 'تجاوز الإدارة'], keywords: [] }),
  Object.freeze({ code: 'ISA 315', framework: 'isa', en: 'Identifying and Assessing the Risks of Material Misstatement', ar: 'تحديد وتقييم مخاطر التحريف الجوهري',
    purpose: 'فهم المنشأة وبيئتها ونظام الرقابة الداخلية، وتحديد مخاطر التحريف الجوهري على مستوى القوائم والتأكيدات.',
    relation: 'يحكم جولتي فهم المنشأة وتقييم المخاطر، ويربط كل خطر بحساب وتأكيد.', lastUpdate: 'النسخة المنقحة (2019) سارية للفترات المبتدئة في أو بعد 15/12/2021',
    source: 'https://www.iaasb.org/publications/international-standard-auditing-315-revised-2019-identifying-and-assessing-risks-material-misstatement', localSource: 'https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx',
    tags: ['مخاطر', 'رقابة داخلية'], keywords: [] }),
  Object.freeze({ code: 'ISA 320', framework: 'isa', en: 'Materiality in Planning and Performing an Audit', ar: 'الأهمية النسبية في تخطيط وتنفيذ المراجعة',
    purpose: 'تحديد الأهمية النسبية للقوائم ككل، وأهمية الأداء، وحد التحريف التافه الواضح.',
    relation: 'يحكم جولة الأهمية النسبية، ونتيجته تُقيّد كل جولة لاحقة.', lastUpdate: 'ساري بصيغته المعاد صياغتها',
    source: 'https://www.iaasb.org/publications/2023-handbook-international-quality-management-auditing-review-other-assurance-and-related-services', localSource: 'https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx',
    tags: ['أهمية نسبية'], keywords: [] }),
  Object.freeze({ code: 'ISA 330', framework: 'isa', en: 'The Auditor’s Responses to Assessed Risks', ar: 'استجابات المراجع للمخاطر المقيَّمة',
    purpose: 'تصميم وتنفيذ استجابات شاملة وإجراءات أخرى تستجيب للمخاطر المقيَّمة على مستوى التأكيد.',
    relation: 'يحكم جولتي الضوابط والإجراءات الجوهرية.', lastUpdate: 'ساري بصيغته المعاد صياغتها',
    source: 'https://www.iaasb.org/publications/2023-handbook-international-quality-management-auditing-review-other-assurance-and-related-services', localSource: 'https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx',
    tags: ['استجابة', 'اختبارات'], keywords: [] }),
  Object.freeze({ code: 'ISA 500', framework: 'isa', en: 'Audit Evidence', ar: 'أدلة المراجعة',
    purpose: 'كفاية وملاءمة أدلة المراجعة، ومصادرها، وموثوقيتها.',
    relation: 'يحكم ربط كل نتيجة بدليل — بوابة لا تُفتح بلا مرجع دليل.', lastUpdate: 'النسخة المنقحة سارية للفترات المبتدئة في أو بعد 15/12/2025',
    source: 'https://www.iaasb.org/publications/international-standard-auditing-500-revised-audit-evidence', localSource: 'https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx',
    tags: ['أدلة'], keywords: [] }),
  Object.freeze({ code: 'ISA 520', framework: 'isa', en: 'Analytical Procedures', ar: 'الإجراءات التحليلية',
    purpose: 'استخدام التحليلات كإجراءات جوهرية وفي المراجعة الختامية، مع تحديد توقع وفرق مقبول.',
    relation: 'يحكم النِسب والاتجاهات وبنفورد وأعمار الذمم.', lastUpdate: 'ساري بصيغته المعاد صياغتها',
    source: 'https://www.iaasb.org/publications/2023-handbook-international-quality-management-auditing-review-other-assurance-and-related-services', localSource: 'https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx',
    tags: ['تحليلات'], keywords: [] }),
  Object.freeze({ code: 'ISA 530', framework: 'isa', en: 'Audit Sampling', ar: 'العينات في المراجعة',
    purpose: 'تصميم العينة وحجمها واختيار البنود وتقييم نتائج العينة وإسقاط التحريفات على المجتمع.',
    relation: 'يحكم جولة الإجراءات الجوهرية عبر عيّنة وحدات نقدية قابلة لإعادة الإنتاج.', lastUpdate: 'ساري بصيغته المعاد صياغتها',
    source: 'https://www.iaasb.org/publications/2023-handbook-international-quality-management-auditing-review-other-assurance-and-related-services', localSource: 'https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx',
    tags: ['عينات'], keywords: [] }),
  Object.freeze({ code: 'ISA 540', framework: 'isa', en: 'Auditing Accounting Estimates', ar: 'مراجعة التقديرات المحاسبية',
    purpose: 'مراجعة التقديرات والإفصاحات المتعلقة بها، بما فيها الخسائر الائتمانية المتوقعة والقيمة العادلة والتحيز الإداري.',
    relation: 'يحكم جولة التقديرات والأحكام ومخصص ECL.', lastUpdate: 'النسخة المنقحة سارية للفترات المبتدئة في أو بعد 15/12/2019',
    source: 'https://www.iaasb.org/publications/international-standard-auditing-540-revised-auditing-accounting-estimates-and-related-disclosures', localSource: 'https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx',
    tags: ['تقديرات', 'تحيز'], keywords: [] }),
  Object.freeze({ code: 'ISA 550', framework: 'isa', en: 'Related Parties', ar: 'الأطراف ذات العلاقة',
    purpose: 'إجراءات تحديد ومراجعة معاملات الأطراف ذات العلاقة والإفصاح عنها.',
    relation: 'يحكم فحص الحسابات الجارية للشركاء والمعاملات غير المعتادة.', lastUpdate: 'ساري بصيغته المعاد صياغتها',
    source: 'https://www.iaasb.org/publications/2023-handbook-international-quality-management-auditing-review-other-assurance-and-related-services', localSource: 'https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx',
    tags: ['أطراف ذات علاقة'], keywords: [] }),
  Object.freeze({ code: 'ISA 570', framework: 'isa', en: 'Going Concern', ar: 'الاستمرارية',
    purpose: 'تقييم مدى ملاءمة استخدام الإدارة لأساس الاستمرارية ووجود شك جوهري.',
    relation: 'يحكم جولة الاستمرارية والأحداث اللاحقة، ويستهلك نتائج السيولة وألتمان Z.', lastUpdate: 'النسخة المنقحة (2024) سارية للفترات المنتهية في أو بعد 15/12/2026',
    source: 'https://www.iaasb.org/publications/international-standard-auditing-570-revised-2024-going-concern', localSource: 'https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx',
    tags: ['استمرارية'], keywords: [] }),
  Object.freeze({ code: 'ISA 450', framework: 'isa', en: 'Evaluation of Misstatements Identified during the Audit', ar: 'تقييم التحريفات المكتشفة خلال المراجعة',
    purpose: 'تجميع التحريفات المؤكدة والتقديرية والمسقطة، وتقييم أثرها على الرأي.',
    relation: 'يحكم جولة الإكمال والتحريفات.', lastUpdate: 'ساري بصيغته المعاد صياغتها',
    source: 'https://www.iaasb.org/publications/2023-handbook-international-quality-management-auditing-review-other-assurance-and-related-services', localSource: 'https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx',
    tags: ['تحريفات'], keywords: [] }),
  Object.freeze({ code: 'ISA 700', framework: 'isa', en: 'Forming an Opinion and Reporting on Financial Statements', ar: 'تكوين الرأي والتقرير عن القوائم المالية',
    purpose: 'تكوين الرأي وصياغة تقرير المراجع، بما فيه المسائل الرئيسية والمسؤوليات.',
    relation: 'يحكم الجولة الأخيرة، ولا تُغلق إلا باعتماد بشري.', lastUpdate: 'ساري بصيغته المعاد صياغتها',
    source: 'https://www.iaasb.org/publications/2023-handbook-international-quality-management-auditing-review-other-assurance-and-related-services', localSource: 'https://soocpa.org.sa/ar/technical/Standards/Pages/default.aspx',
    tags: ['رأي', 'تقرير'], keywords: [] })
]);

/** كل المعايير في فهرس واحد. */
export const STANDARDS = Object.freeze([...REPORTING_STANDARDS, ...AUDITING_STANDARDS]);

const BY_CODE = new Map(STANDARDS.map(s => [s.code, s]));

export function getStandard(code) {
  return BY_CODE.get(String(code).trim()) ?? null;
}

export function byFramework(framework) {
  return STANDARDS.filter(s => s.framework === framework);
}

/** بحث نصي بسيط عبر الكود والاسم والوسوم والكلمات المفتاحية. */
export function searchStandards(query) {
  const q = String(query ?? '').trim().toLowerCase();
  if (!q) return STANDARDS;
  return STANDARDS.filter(s =>
    s.code.toLowerCase().includes(q) ||
    s.ar.includes(q) ||
    s.en.toLowerCase().includes(q) ||
    s.tags.some(t => t.includes(q)) ||
    s.keywords.some(k => k.toLowerCase().includes(q)));
}
